FROM python:3.8-slim

WORKDIR /app

COPY . .

RUN apt-get update -y && \
    apt-get install nano telnet curl -y && \
    pip3 install -U pip && \
    pip3 install -r requirements.txt

CMD ["python3", "main.py"]
