version: "3.2"

services:
  db:
    container_name: mongo-dev
    image: mongo:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks: 
      - mongo-compose-network
    ports:
      - '27017:27017'
    volumes: 
      - ./database:/data/db
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - db
    networks: 
      - mongo-compose-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-dev
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=tribes
    ports:
      - '8081:8081'
    volumes: 
      - ./database:/data/db
  redis:
    container_name: redis-queue
    image: redis
    ports:
      - '6379:6379'
  api:
    build:
      dockerfile: Dockerfile
      context: .
    image: face-ekyc-api
    container_name: face-ekyc_api
    network_mode: host
  gateway:
    build:
      dockerfile: Dockerfile_gateway
      context: .
    image: face-ekyc-model
    container_name: face-ekyc_model
    network_mode: host
  server:
    build:
      dockerfile: Dockerfile_server
      context: .
    image: face-ekyc-indexing
    container_name: face-ekyc_indexing
    network_mode: host

networks:
  mongo-compose-network:
    driver: bridge
