version: "3.2"

services:
  mongodb:
    container_name: mongo_database
    image: mongo:6.0.1
    ports:
      - '17017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=P4ssW0rD
    volumes: 
      - ./volumes/mongo:/data/db
  
  mongo-express:
    container_name: mongo_express
    image: mongo-express:1.0.0-alpha
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=P4ssW0rD
    ports:
      - '18081:8081'

  redis:
    container_name: redis_queue
    image: redis:7.0.4
    ports:
      - '16379:6379'
    volumes:
      - ./volumes/redis:/data

  api:
    build: .
    image: hoangph3/face-kyc-api:1.0.0
    container_name: face_kyc-api
    volumes:
      - ./volumes/api:/app/model
    depends_on:
      - redis
    network_mode: host
    environment:
      - API_HOST=127.0.0.1
      - API_PORT=8999
      - DIM_MODEL=128
      - METRIC_MODEL=cosine
      - MATCHED_SCORE=0.90
      - SERVING_URL=https://127.0.0.1:8501/api/user/pattern
      - MONGO_USER=admin
      - MONGO_PASSWORD=P4ssW0rD
      - MONGO_PORT=17017
      - REDIS_PORT=16379
