version: "3.2"

services:
  mongodb:
    container_name: mongo_database
    image: mongo:6.0.1
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=P4ssW0rD
    volumes: 
      - mongo-data:/data/db
  
  mongo-express:
    container_name: mongo_express
    image: mongo-express:1.0.0-alpha
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=P4ssW0rD
    ports:
      - '8081:8081'

  redis:
    container_name: redis_queue
    image: redis:7.0.4
    ports:
      - '6379:6379'
    volumes:
      - /var/lib/docker/redis-data:/data

  api:
    # build: .
    image: hoangph3/face-kyc-api:v0.0.1
    container_name: face_kyc-api
    ports:
      - '8999:8999'
    volumes:
      - /var/lib/docker/face-kyc-api/ckpt/:/app/ckpt/
    depends_on:
      - redis
    network_mode: host

volumes:
  mongo-data:
    driver: local

