FROM hoangph3/python-opencv:py3.7-cv4.0.0

WORKDIR /app

COPY . .

RUN apt-get update -y && \
    apt-get install nano telnet curl -y && \
    pip3 install -U pip && \
    pip3 install opencv-python~=4.1.0 && \
    pip3 install -r requirements.txt 

CMD ["python3", "main.py"]
