FROM hoangph3/l4t-opencv:4.5.2-on-nano-r32.6.1

WORKDIR /app

COPY . .

RUN apt-get update -y && \
    apt-get install nano telnet curl -y && \
    pip3 install -U pip && \
    pip3 install -r requirements.txt

CMD ["python3", "main.py"]