version: "3.2"

services:
  face_recognition:
    build: .
    image: hoangph3/face-recognition-gateway:v0.0.1
    container_name: face_recognition_gateway
    ports:
      - '8501:8501'
    network_mode: host
